# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe2fa931596007daaab4d4586b4ceaeb04237dbfde548519248e122819e13751035885250926ce52265270812be93b84cfb4443afdb0a66ec249394e2df0d8f1

test:
  secret_key_base: 9bd8c73da28baa4626e44b21a1a33ed59b718e993622bf800a357ad56bcd32dd3e90296d9852cb4eab34930d6460660bf72a83aa60b24e197ca98c346eaa2ec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
